# Generated by Django 5.1.1 on 2024-10-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_name_user_firstname_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=8, unique=True, verbose_name='Preferred Name'),
        ),
    ]
